apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixel-app
  labels:
    app: static
spec:
  replicas: 3
  selector:
    matchLabels:
      app: static
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
        - name: nginx
          image: adesh0303/eks-app:91a777cc2b22170de45c4f44008f53fee986482b
          ports:
            - containerPort: 80
