apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixel-app
  labels:
    app: static
spec:
  replicas: 3
  selector:
    matchLabels:
      app: static
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
        - name: nginx
          image: adesh0303/eks-app:0100f75a5843d30f141a8437b9624b821859e993
          ports:
            - containerPort: 80
